;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-intermediate-reader.ss" "lang")((modname CoastlineMiles) (read-case-sensitive #t) (teachpacks ((lib "image.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp") (lib "batch-io.rkt" "teachpack" "2htdp"))) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ((lib "image.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp") (lib "batch-io.rkt" "teachpack" "2htdp")) #f)))
; A coast is (make-coast n c no) where
; n is a string (state name), c is a number (coastline reported)
; and no is a number (coastline reported by NOAA).
(define-struct coast [name coast noaa-coast])

(define STATES (list
                (make-coast "Alaska" 6640 33904)
                (make-coast "Florida" 1350 8436)
                (make-coast "Louisiana" 397 7721)
                (make-coast "Maine" 228 3478)
                (make-coast "California" 840 3427)
                (make-coast "North Carolina" 301 3375)
                (make-coast "Texas" 367 3359)
                (make-coast "Virginia" 112 3315)
                (make-coast "Michigan" 0 3224)
                (make-coast "Maryland" 31 3190)
                (make-coast "Washington" 157 3026)
                (make-coast "South Carolina" 187 2876)
                (make-coast "New York" 127 2625)
                (make-coast "Georgia" 100 2344)
                (make-coast "New Jersey" 130 1792)
                (make-coast "Massachusetts" 192 1519)
                (make-coast "Oregon" 296 1410)
                (make-coast "Hawaii" 750 1052)
                (make-coast "Wisconsin" 0 820)
                (make-coast "Connecticut" 96 618)
                (make-coast "Alabama" 53 607)
                (make-coast "Rhode Island" 40 384)
                (make-coast "Delaware" 28 381)
                (make-coast "Mississippi" 44 359)
                (make-coast "Ohio" 0 312)
                (make-coast "Minnesota" 0 189)
                (make-coast "Pennsylvania" 0 140)
                (make-coast "New Hampshire" 13 131)
                (make-coast "Illinois" 0 63)
                (make-coast "Indiana" 0 45)
                (make-coast "Arizona" 0 0)
                (make-coast "Arkansas" 0 0)
                (make-coast "Colorado" 0 0)
                (make-coast "Idaho" 0 0)
                (make-coast "Iowa" 0 0)
                (make-coast "Kansas" 0 0)
                (make-coast "Kentucky" 0 0)
                (make-coast "Missouri" 0 0)
                (make-coast "Montana" 0 0)
                (make-coast "Nebraska" 0 0)
                (make-coast "Nevada" 0 0)
                (make-coast "New Mexico" 0 0)
                (make-coast "North Dakota" 0 0)
                (make-coast "Oklahoma" 0 0)
                (make-coast "South Dakota" 0 0)
                (make-coast "Tennessee" 0 0)
                (make-coast "Utah" 0 0)
                (make-coast "Vermont" 0 0)
                (make-coast "West Virginia" 0 0)
                (make-coast "Wyoming" 0 0)))
  